xpcall(function()
    function MainLoop()
        xpcall(function()
            Framework:setVideoMemory(1, 1, 0xffff0000)
        end, function(msg)
            print(msg)
        end)
    end
end, function(msg)
    print(msg)
end)
