xpcall(function()
    os.execute("chcp 65001 > NUL")
    print("Hello 👋")
    require "init"
    Framework:init()
    function MainLoop()
        xpcall(function()
            Framework:fixFPS()
            Director:update()
        end, function(msg)
            print(msg)
        end)
    end
end, function(msg)
    print(msg)
end)
